she_codes_news/news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.StoryView.as_view(), name='story'),
    path('add-story/', views.AddStoryView.as_view(), name='newStory'),
    # path('<int:pk>/comment', views.AddCommentView.as_view(), name='addComment')
]

she_codes_news/she_codes_news/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('news/', include('news.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls'))
]

she_codes_news/users/urls.py
from django.urls import path
from .views import CreateAccountView, Profile, EditAccountView

app_name = 'users'
urlpatterns = [
    path('create-account/', CreateAccountView.as_view(), name='createAccount'),
    path('<int:pk>/', Profile.as_view(), name='profile'),
    path('<int:pk>/edit', EditAccountView.as_view(), name='editAccount')
]

she_codes_news/news/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth import get_user_model

# # News Category Model
# class Category(models.Model):
#     title=models.CharField(max_length=200)
#     category_image=models.ImageField(upload_to='images/')

#     class Meta:
#         verbose_name_plural='Categories'

#     def __str__(self):
#         return self.title

# News Story Model
class NewsStory(models.Model):
    title = models.CharField(max_length=200)
    # category=models.TextChoices(Category, on_delete=models.CASCADE)
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    pub_date = models.DateTimeField()
    content = models.TextField()
    # image = models.ImageField(upload_to='images/')

    class Meta:
        verbose_name_plural='News Stories'

    def __str__(self):
        return self.title
    
#Comments Model
# class Comment(models.Model):
#     news_story=models.ForeignKey(NewsStory, on_delete=models.CASCADE)
#     author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
#     comment_date_time=models.DateTimeField(auto_now_add=True)
#     comment=models.TextField()
#     # admin can moderate comments for spam in admin panel by setting status to false
#     status=models.BooleanField(default=True)

#     def __str__(self):
#         return self.comment

she_codes_news/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import UserManager


class CustomUser(AbstractUser):
    pass
    # id = models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')
    # username = models.CharField(max_length=100, unique=True, verbose_name='username')
    # username = models.CharField(max_length=100, unique=True, primary_key=True, verbose_name='username')
    # first_name = models.CharField(max_length=100)
    # last_name = models.CharField(max_length=100)
    # email = models.EmailField(max_length=256, unique=True, verbose_name='email')
    # date_joined = models.DateField(auto_now_add=True)
    # last_login = models.DateTimeField(blank=True, null=True, verbose_name='last login')
    # is_active = models.BooleanField(default=True)
    # is_admin = models.BooleanField(default=False)
    # profile_image = models.ImageField(upload_to='images/profile', null=True)
    # biography = models.TextField(blank=True, null=True)
    # user_permissions = models.ManyToManyField(blank=True, verbose_name='user permissions')
    # interests = 
    # login_status = 

    def __str__(self):
        return self.username

she_codes_news/news/forms.py
from django import forms
from django.forms import ModelForm
from .models import NewsStory
# from .models import NewsStory, Comment

class StoryFrom(ModelForm):
    class Meta:
        model = NewsStory
        fields = ['title', 'pub_date', 'content']
        # fields = ['title', 'pub_date', 'image', 'content', 'comment']
        widgets = {
            'pub_date': forms.DateInput(
                format='%d/%m/%d',
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Select a date',
                    'type': 'date'
                }
            )
        }

she_codes_news/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'email']
        # fields = ['username', 'first_name', 'last_name', 'email']
        # interests, bio, profile picture

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'email']
        # fields = ['username', 'first_name', 'last_name', 'email']

she_codes_news/news/views.py
from django.views import generic
from django.urls import reverse_lazy
from .models import NewsStory
from .forms import StoryFrom
# from .forms import StoryFrom, Comment


class IndexView(generic.ListView):
    template_name = 'news/index.html'
    context_object_name = "all_stories"

    def get_queryset(self):
        '''Return all news stories.'''
        return NewsStory.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['latest_stories'] = NewsStory.objects.all().order_by('-pub_date')[:4]
        return context

class StoryView(generic.DetailView):
    model = NewsStory
    template_name = 'news/story.html'
    context_object_name = 'story'

class AddStoryView(generic.CreateView):
    form_class = StoryFrom
    context_object_name = 'storyform'
    template_name = 'news/createStory.html'
    success_url = reverse_lazy('news:index')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
    
# class AddCommentView(generic.CreateView):
#     form_class = Comment

#     def get(self, request, *args, **kwargs):
#         return ("news:story", pk==self.kwargs.get("pk"))
    
#     def form_valid(self, form):
#         form.instance.author = self.request.user
#         pk = self.kwargs.get("pk")
#         form.instance.story = get_object_or_404(NewsStory, pk=pk)
#         return super().form_valid(form)
    
#     def get_success_url(self):
#         return reverse_lazy('news:story', kwargs={'pk':self.kwargs.get("pk")})

she_codes_news/users/views.py
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.views import generic
from .models import CustomUser
from .forms import CustomUserCreationForm, CustomUserChangeForm
from news.models import NewsStory

class CreateAccountView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'users/createAccount.html'

class EditAccountView(generic.UpdateView):
    form_class = CustomUserChangeForm
    success_url = reverse_lazy('users:profile')
    template_name = 'users/createAccount.html'
    
class Profile(generic.DetailView):
    model = CustomUser
    template_name = 'users/userProfile.html'
    context_object_name = 'profile'

    def get_object(self, *args, **kwargs):
        return get_object_or_404(CustomUser, username=self.kwargs['username'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['all_stories'] = NewsStory.objects.filter(author=self.kwargs['pk']).order_by('-pub_date')
        return context

she_codes_news/news/templates/news/createStory.html
{% extends "base.html" %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="submit">
</form>
{% endblock %}

she_codes_news/news/templates/news/index.html
    {% extends 'base.html' %}
    {% load static %}

    {% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
    {% endblock %}

    {% block content %}
    <br>
    <a href="{% url 'news:newStory' %}">Write New Story</a>
    <h2>Latest News</h2>

    <div id="latest-stories">
        {% if latest_stories %}
            {% for story in latest_stories %}
                {% include './storyCard.html' with story=story position=forloop.counter %}
                <!-- <p>{{ story.title }}</p> -->
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>

    <div id="all-stories">
        {% if latest_stories %}
            {% for story in all_stories %}
            {% include './storyCard.html' with story=story position=forloop.counter %}
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>

    {% endblock %}

she_codes_news/news/templates/news/story.html
{% extends 'base.html' %}
{% load static %}

{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
    {% endblock %}

{% block content %}
<div id="story-wrapper">
    <h2>{{ story.title }}</h2>
    <h4>{{ story.author }}</h4>
    <div id="story-content">
        {% if story.image %}
        <img scr="{{ story.image}}">
        {% else %}
        <img src="{% static '/news/images/placeholder-5.jpg' %}">
        {% endif %}
        {{ story.content|linebreaks }}
    </div>
</div>
{% endblock %}

she_codes_news/news/templates/news/storyCard.html
<div class="story-card" id="story-card-{{ position }}">
    <a href="{% url 'news:story' story.id %}">
        {% if story.image %}
            <img src="{{ story.image }}">
        {% else %}
            <img src="https://picsum.photos/600">
        {% endif %}
        <div class="story-card-text">
            <h3>{{ story.title }}</h3>
            <h4>{{ story.author }}</h4>
            <h4>{{ story.pub_date }}</h4>
        </div>
    </a>
</div>

she_codes_news/templates/base.html
{% load static %}
<!doctype html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>She Codes News</title>
        <meta name="description" content="">
        <meta name="author" content="Denise">
        <link href="https://fonts.googleapis.com/css?family=Manjari&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
        {% block stylesheets %}{% endblock %}
    </head>

    <body>
        <header>
            <div id="header-text">
                <a id="header-link" href="{% url 'news:index' %}">
                    <h1>She {Codes} News</h1>
                </a>
            </div>
            {% include './nav.html' %}
        </header>

        <!-- content blocks here -->
        {% block content %}{% endblock %}
    </body>
</html>

she_codes_news/templates/nav.html
<nav>
    <a href="{% url 'news:index' %}">Home</a>
    {% if request.user.is_authenticated %}
        <a href="#">{{ user.username }}</a>
        <a href="{% url 'logout' %}">Logout</a>
    {% else %}
        <a href="{% url 'login' %}">Login</a>
    {% endif %}
</nav>

she_codes_news/users/templates/users/createAccount.html
{% extends 'base.html' %}

{% block content %}
  <h2>Create Account</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create Account</button>
  </form>
{% endblock %}

she_codes_news/users/templates/users/userProfile.html
{% extends 'base.html' %}

{% block content %}
<!-- User Profile -->

<!-- User Stories -->
<h2> Stories by {{ author.username }} <h2>
<div id="latest-stories">
    {% if user_stories %}
        {% for story in author.newsstory_set.all %}
            {% include './storyCard.html' with story=story position=forloop.counter %}
        {% endfor %}
    {% else %}
        <p> No stories available</p>
    {% endif %}
</div>

{% endblock %}